//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuGiaoNhan
    {
        public int MaPhieuGiaoNhan { get; set; }
        public int MaThietBi { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual PhieuGiaoNhan PhieuGiaoNhan { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
