//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public int MaThietBi { get; set; }
        public int MaLoai { get; set; }
        public Nullable<System.DateTime> NgayDuaVaoSuDung { get; set; }
        public int TinhTrang { get; set; }
    
        public virtual Loai Loai { get; set; }
        public virtual TinhTrang TinhTrang1 { get; set; }
    }
}
